import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300' ,'400', '500', '600', '700', '800', '900'],
  variable: '--font-roboto', // opcional, para usarlo con Tailwind o CSS
})

export const metadata: Metadata = {
  title: "Ivan navas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        {children}
      </body>
    </html>
  );
}
